apiVersion: v1
kind: Service
metadata:
  labels:
    svc-name: cas-mysql
  name: cas-mysql
spec:
  ports:
  - nodePort: 30218
    port: 30218
    protocol: TCP
    targetPort: 3306
  selector:
    pod-name: cas-mysql
  sessionAffinity: None
  type: NodePort
